units:
  dx: 0.5u

points:
  zones:
    matrix:
      anchor:
        shift: [100,-100]
      columns:
        pinky:
          key:
            column_net: P21
            mirror.column_net: P2
        ring:
          key:
            stagger: u/2
            column_net: P20
            mirror.column_net: P3
        middle:
          key:
            stagger: u/2
            column_net: P19
            mirror.column_net: P4
        index:
          key:
            stagger: -u/2
            column_net: P18
            mirror.column_net: P5
        inner:
          key:
            column_net: P15
            mirror.column_net: P6
      rows:
        bottom:
          row_net: P8
          mirror.row_net: P8
        home:
          row_net: P16
          mirror.row_net: P16
        top:
          row_net: P14
          mirror.row_net: P14
    thumb:
      anchor:
        ref: matrix_inner_bottom
        shift: [-u,-u]
      rows:
        cluster:
          row_net: P9
      columns:
          inner:
            key:
              column_net: P19
              mirror.column_net: P4
          middle:
            key:
              column_net: P18
              mirror.column_net: P5
          outer:
            key:
              column_net: P15
              mirror.column_net: P6
  rotate: -17.5
  mirror:
    ref: thumb_outer_cluster
    distance: 2u

outlines:
  raw_outline:
    - what: rectangle
      where: true
      size: [u,u]
  keys_ref:
    - what: rectangle
      where: true
      size: [u-0.25,u-0.25]
  centre:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_matrix_inner_top
          shift: [dx, dx-4u]
        - ref: matrix_inner_top
          shift: [dx, dx-4u]
        - ref: matrix_inner_top
          shift: [dx, dx]
        - ref: mirror_matrix_inner_top
          shift: [dx, dx]
  centre2:
    - what: polygon
      operation: stack
      points:
        - ref: thumb_outer_cluster
          shift: [0.5u, 0.5u]
        - ref: thumb_outer_cluster
          shift: [0.5u, -0.5u]
        - ref: mirror_thumb_outer_cluster
          shift: [0.5u, -0.5u]
        - ref: mirror_thumb_outer_cluster
          shift: [0.5u, 0.5u]
     
  joined_outline:
    - name: raw_outline
    - operation: add
      name: centre

  joined2:
    - name: joined_outline
    - operation: add
      name: centre2


  visual1:
    - name: raw_outline
    - operation: subtract
      name: keys_ref
 
  visual2:
    - name: joined2
    - operation: subtract
      name: keys_ref
     
pcbs:
  ergogen_pcb_tutorial:
    outlines:
      main:
        outline: joined2
    footprints:
      mx_hotswap:
        what: mx
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      promicro:
        what: promicro
        params:
          orientation: "down"
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [0,-u]
          rotate: -90                      
       

