units:
  dx: 0.5u

points:
  zones:
    matrix:
      anchor:
        shift: [100,-100]
      columns:
        pinky:
          key:
            column_net: P017
            mirror.column_net: P031
        ring:
          key:
            stagger: u/2
            column_net: P020
            mirror.column_net: P029
        middle:
          key:
            stagger: u/2
            column_net: P022
            mirror.column_net: P002
        index:
          key:
            stagger: -u/2
            column_net: P024
            mirror.column_net: P115
        inner:
          key:
            column_net: P100
            mirror.column_net: P113
      rows:
        bottom:
          row_net: P104
          mirror.row_net: P104
        home:
          row_net: P010
          mirror.row_net: P010
        top:
          row_net: P111
          mirror.row_net: P111
    thumb:
      anchor:
        ref: matrix_inner_bottom
        shift: [-u,-u]
      rows:
        cluster:
          row_net: P106
      columns:
          inner:
            key:
              column_net: P022
              mirror.column_net: P002
          middle:
            key:
              column_net: P024
              mirror.column_net: P115
          outer:
            key:
              column_net: P100
              mirror.column_net: P113
  rotate: -17.5
  mirror:
    ref: thumb_outer_cluster
    distance: 2u

outlines:
  raw_outline: ##with 3mm margin
    - what: rectangle
      where: true
      size: [u+4,u+4]
  keys_ref:
    - what: rectangle
      where: true
      size: [u,u]
  centre:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_matrix_inner_top
          shift: [dx, dx-4u]
        - ref: matrix_inner_top
          shift: [dx, dx-4u]
        - ref: matrix_inner_top
          shift: [dx+2, dx+2]
        - ref: mirror_matrix_inner_top
          shift: [dx+2, dx+2]
  centre2:
    - what: polygon
      operation: stack
      points:
        - ref: thumb_outer_cluster
          shift: [0.5u, 0.5u]
        - ref: thumb_outer_cluster
          shift: [0.5u+2, -0.5u-2]
        - ref: mirror_thumb_outer_cluster
          shift: [0.5u+2, -0.5u-2]
        - ref: mirror_thumb_outer_cluster
          shift: [0.5u, 0.5u]
     
  joined_outline:
    - name: raw_outline
    - operation: add
      name: centre

  joined2:
    - name: joined_outline
    - operation: add
      name: centre2
      fillet: 2.5


  visual1:
    - name: raw_outline
    - operation: subtract
      name: keys_ref
 
  visual2:
    - name: joined2
    - operation: subtract
      name: keys_ref
     
pcbs:
  ergogen_pcb_ergo_wip:
    outlines:
      main:
        outline: joined2
    footprints:
      mx_hotswap:
        what: mx
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -0.5u+1]  
          rotate: 0
      mcu:
        what: nice_nano_josh
        params:

          orientation: "up"
          BNeg: pos
          BPos: BPos
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [0,-1.25u]
          rotate: -90
          
      jst connector:
        what: jstph
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]  # Same anchor as Pro Micro
          shift: [0, -2.25u] 
          rotate: 0  
        params:

          pos: pos
          neg: neg
      slider:
        what: custom_slider
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]  # Same anchor as Pro Micro
          shift: [0, -3.5u+1.5] 
          rotate: 0  
        params:

          from: BPos
          to: neg
      

## to build in terminal:
## cd Desktop\Github\pcb_ergo\Ergogen
## ergogen .

                                 
       

